name: Test Python
on:
  push:
    branches: [main]
  workflow_dispatch:
  pull_request:

jobs:
  ruff:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install ruff
        run: pip install ruff
      - name: Run ruff format
        run: ruff format .
      - name: Check for changes
        run: |
          git status
          git diff --quiet || (echo "Changes detected after formatting. Please run 'ruff format' locally and commit the changes." && exit 1)
      - name: Run ruff check
        run: ruff check .

  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry ${{ matrix.python-version }}
        run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'
      - run: poetry install
      - run: poetry run pytest